name: Full Stack CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install all dependencies (root)
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run UI tests
        run: npx playwright test

      - name: Install backend deps
        working-directory: ./server
        run: npm install

      - name: Start backend server
        working-directory: ./server
        run: |
          node index.js &
          sleep 5

      - name: Install frontend deps
        working-directory: ./client
        run: npm install

      - name: Build frontend
        working-directory: ./client
        run: CI=false npm run build
